# Generated by Django 4.2.7 on 2023-11-05 12:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PantoneColorPrototype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hex", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="PantoneColor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("number", models.CharField(max_length=255)),
                ("hex", models.CharField(max_length=255)),
                (
                    "prototype",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="chameleon_api.pantonecolorprototype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DailyColors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(default=datetime.date.today, verbose_name="Date"),
                ),
                ("colors", models.ManyToManyField(to="chameleon_api.pantonecolor")),
            ],
        ),
    ]
