# Generated by Django 4.2.6 on 2023-12-21 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chameleon_api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="current_streak",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="total_photos",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="total_rating",
        ),
    ]
