# Generated by Django 4.2.6 on 2023-12-14 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chameleon_api", "0003_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="photos",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="rating",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="profile",
            name="streak",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ratedphoto",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chameleon_api.profile",
            ),
        ),
    ]
