# Generated by Django 4.2.6 on 2023-12-14 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("chameleon_api", "0004_profile_photos_profile_rating_profile_streak_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="streak",
            new_name="current_streak",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="photos",
            new_name="total_photos",
        ),
        migrations.RenameField(
            model_name="profile",
            old_name="rating",
            new_name="total_rating",
        ),
        migrations.AlterField(
            model_name="ratedphoto",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="chameleon_api.profile",
            ),
        ),
    ]
